robot_radius: 0.25

plugins:
- {name: static_layer, type: "costmap_2d::StaticLayer"}
- {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
- {name: inflation_layer, type: "costmap_2d::InflationLayer"}

obstacle_layer:
  obstacle_range: 2.5
  raytrace_range: 13.0
  max_obstacle_height: 0.7
  observation_sources: rplidar d435
  publish_voxel_map: true
  rplidar:
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: false
    inf_is_valid: true
  d435:
    data_type: PointCloud2
    topic: rtabmap/depth/color/obstacles
    marking: true
    clearing: true

inflation_layer:
  inflation_radius: 0.1
