
robot_radius: 0.178
inflation_radius: 0.1

obstacle_layer:
  obstacle_range: 2.5
  raytrace_range: 3.0
  max_obstacle_height: 0.7
  observation_sources: rplidar d435
  rplidar:
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    inf_is_valid: true
  d435:
    data_type: PointCloud2
    topic: rtabmap/depth/color/obstacles
    marking: true
    clearing: true
