robot_radius: 0.2

plugins:
- {name: static_layer, type: "costmap_2d::StaticLayer"}
- {name: depth_layer, type: "costmap_2d::ObstacleLayer"}
- {name: inflation_layer, type: "costmap_2d::InflationLayer"}

depth_layer:
  obstacle_range: 2.5
  raytrace_range: 9.0
  max_obstacle_height: 0.7
  track_unknown_space: true
  observation_sources: d435
  d435:
    data_type: PointCloud2
    topic: rtabmap/depth/color/obstacles
    marking: true
    clearing: true

inflation_layer:
  cost_scaling_factor: 5.0
  inflation_radius: 0.5
