robot_radius: 0.25

plugins:
- {name: static_layer, type: "costmap_2d::StaticLayer"}
- {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
- {name: inflation_layer, type: "costmap_2d::InflationLayer"}

obstacle_layer:
  obstacle_range: 2.5
  raytrace_range: 13.0
  max_obstacle_height: 0.7
  observation_sources: rplidar d435
  rplidar:
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    inf_is_valid: true
    expected_update_rate: 0.15
  d435:
    data_type: PointCloud2
    topic: rtabmap/depth/color/obstacles
    marking: true
    clearing: true
    expected_update_rate: 0.07

inflation_layer:
  inflation_radius: 0.1
